# run: conda env create --file environment.yml
name: schneider_notebook_env
channels:
    - conda-forge
dependencies:
    - python==3.12
    - ipywidgets
    - pip
    - pip:
      - matplotlib
      - lerner-lab-to-nwb @ git+https://github.com/catalystneuro/lerner-lab-to-nwb.git@main